preload = /home/alex/Pictures/wallpapers/main.png
wallpaper = DP-1,/home/alex/Pictures/wallpapers/main.png
wallpaper = DP-2,/home/alex/Pictures/wallpapers/main.png
wallpaper = DP-3,/home/alex/Pictures/wallpapers/main.png
splash = false
