$font = Noto Sans CJK JP

general {
    hide_cursor = false
}

background {
    monitor =
    color = rgb(080B10)
}

input-field {
    monitor =
    size = 360, 54
    outline_thickness = 2
    inner_color = rgb(10151D)
    outer_color = rgb(315DA8)
    check_color = rgb(4F8CFF)
    fail_color = rgb(B94C5A)
    font_color = rgb(EAF1FF)
    fade_on_empty = false
    rounding = 14
    font_family = $font
    placeholder_text = Password
    fail_text = $PAMFAIL
    check_text = Authenticating...
    dots_spacing = 0.25
    position = 0, -32
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(EAF1FF)
    font_size = 76
    font_family = $font
    position = 0, 130
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = rgb(8996AA)
    font_size = 18
    font_family = $font
    position = 0, 70
    halign = center
    valign = center
}

label {
    monitor =
    text = Locked
    color = rgb(75A7FF)
    font_size = 12
    font_family = $font
    position = 0, 14
    halign = center
    valign = center
}
